name: heystone
version: 0.1.0
synopsis: Haskell bindings for the Keystone assembler framework
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
- cbits/include/*
category: Bindings, Compilers/Interpreters, Assembler
tested-with: GHC ==8.0.2, GHC ==9.2.3
license: GPL-2
license-file: LICENSE

github: raehik/heystone
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Adrian Herrera, Ben Orchard

# TODO 2022-04-22 This will be supported eventually - I looked just now, and
# there was a fix 10 hours ago! But it'll take a while to trickle down into an
# hpack release, and then that release in Stack.
language: GHC2021

# raehik's extensions (GHC 9.2; last updated: 2022-06-15)
default-extensions:
# syntax that should be default
- EmptyCase
- LambdaCase
- InstanceSigs
- BangPatterns
- ExplicitNamespaces # 7.6

## deriving-related
#- DerivingStrategies # 8.2
#- DerivingVia # 8.6
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift

# features that should be default
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- GADTs
- PolyKinds
- RoleAnnotations # 7.8
- RankNTypes

# other features
- TypeApplications # 8.0
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash
#- ImportQualifiedPost # 8.10
#- StandaloneKindSignatures # 8.10

# essential, but can break things, so be wary
- ScopedTypeVariables # changes type var scoping quite dramatically
- TypeOperators # interferes with the old `*` type

# useful extensions to know about, but which must be specified on-demand
#- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >= 4.9 && < 5
- bytestring ^>= 0.11.3.1
- transformers >= 0.5 && < 0.7

library:
  source-dirs: src
  build-tools:
  - c2hs ^>= 0.28.8
  include-dirs:
  - cbits/include
  c-sources:
  - cbits/src/*
  pkg-config-dependencies:
  - keystone
